# Generated by Django 2.0.6 on 2019-12-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.SmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('fixed_phone', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 't_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.CharField(blank=True, max_length=100, null=True)),
                ('press', models.CharField(blank=True, max_length=20, null=True)),
                ('press_date', models.DateField(blank=True, null=True)),
                ('press_count', models.CharField(blank=True, max_length=20, null=True)),
                ('print_date', models.DateField(blank=True, null=True)),
                ('print_count', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.IntegerField(blank=True, db_column='ISBN', null=True)),
                ('types', models.CharField(blank=True, max_length=20, null=True)),
                ('make_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('word_num', models.IntegerField(blank=True, null=True)),
                ('page_num', models.SmallIntegerField(blank=True, null=True)),
                ('book_size', models.SmallIntegerField(blank=True, null=True)),
                ('paper', models.CharField(blank=True, max_length=10, null=True)),
                ('pack', models.CharField(blank=True, max_length=10, null=True)),
                ('editor_rec', models.TextField(blank=True, null=True)),
                ('content_validity', models.TextField(blank=True, null=True)),
                ('author_validity', models.TextField(blank=True, null=True)),
                ('list', models.TextField(blank=True, null=True)),
                ('media_reviews', models.TextField(blank=True, null=True)),
                ('illustrate', models.TextField(blank=True, db_column='Illustrate', null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=30, null=True)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('all_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TAddress')),
            ],
            options={
                'db_table': 't_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TOrderAll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TBook')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TOrder')),
            ],
            options={
                'db_table': 't_order_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TShopCar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('all_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_shop_car',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TShopCarAll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_status', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TBook')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TShopCar')),
            ],
            options={
                'db_table': 't_shop_car_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=30, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tshopcar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TUser'),
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TUser'),
        ),
        migrations.AddField(
            model_name='tbook',
            name='pid',
            field=models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TCategory'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangdang.TUser'),
        ),
    ]
