import os
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dd.settings")
django.setup()


# -----------------TCategory 书籍分类数据------------------------------
# from dangdang.models import TCategory

# TCategory.objects.create(title="电子书 /当当阅读器", pid=None)
# TCategory.objects.create(title="小说", pid=None)
# TCategory.objects.create(title="文艺", pid=None)
# TCategory.objects.create(title="青春文学 /动漫 · 幽默", pid=None)
# TCategory.objects.create(title="童书", pid=None)
# TCategory.objects.create(title="生活", pid=None)
# TCategory.objects.create(title="人文社科", pid=None)
# TCategory.objects.create(title="经管", pid=None)
# TCategory.objects.create(title="励志/成功", pid=None)
# TCategory.objects.create(title="科技", pid=None)
# TCategory.objects.create(title="英文原版书 港台图书", pid=None)
# TCategory.objects.create(title="当当出版", pid=None)
# TCategory.objects.create(title="期刊", pid=None)
# TCategory.objects.create(title="文化礼品/工艺品", pid=None)

# TCategory.objects.create(title="教材", pid=1)
# TCategory.objects.create(title="外语", pid=1)
# TCategory.objects.create(title="考试", pid=1)
# TCategory.objects.create(title="中小学教辅", pid=1)
# TCategory.objects.create(title="文学", pid=4)
# TCategory.objects.create(title="传记", pid=4)
# TCategory.objects.create(title="艺术", pid=4)
# TCategory.objects.create(title="0-2", pid=6)
# TCategory.objects.create(title="3-6", pid=6)
# TCategory.objects.create(title="7-10", pid=6)
# TCategory.objects.create(title="11-14", pid=6)
# TCategory.objects.create(title="科普/百科", pid=6)
# TCategory.objects.create(title="绘本", pid=6)
# TCategory.objects.create(title="文学", pid=6)
# TCategory.objects.create(title="孕期", pid=7)
# TCategory.objects.create(title="两性", pid=7)
# TCategory.objects.create(title="育儿/早教", pid=7)
# TCategory.objects.create(title="亲子/家教", pid=7)
# TCategory.objects.create(title="保健", pid=7)
# TCategory.objects.create(title="运动", pid=7)
# TCategory.objects.create(title="美妆", pid=7)
# TCategory.objects.create(title="手工/DIY", pid=7)
# TCategory.objects.create(title="美食", pid=7)
# TCategory.objects.create(title="旅游", pid=7)
# TCategory.objects.create(title="休闲", pid=7)
# TCategory.objects.create(title="家庭/家居", pid=7)
# TCategory.objects.create(title="风水/占卜", pid=7)
# TCategory.objects.create(title="历史", pid=8)
# TCategory.objects.create(title="古籍", pid=8)
# TCategory.objects.create(title="哲学/宗教", pid=8)
# TCategory.objects.create(title="文化", pid=8)
# TCategory.objects.create(title="政治/军事", pid=8)
# TCategory.objects.create(title="法律", pid=8)
# TCategory.objects.create(title="社会科学", pid=8)
# TCategory.objects.create(title="管理", pid=9)
# TCategory.objects.create(title="投资理财", pid=9)
# TCategory.objects.create(title="经济", pid=9)
# TCategory.objects.create(title="科普", pid=11)
# TCategory.objects.create(title="建筑", pid=11)
# TCategory.objects.create(title="医学", pid=11)
# TCategory.objects.create(title="计算机", pid=11)
# TCategory.objects.create(title="农林", pid=11)
# TCategory.objects.create(title="自然科学", pid=11)
# TCategory.objects.create(title="工业", pid=11)
